# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI-CD 

on:
  push:
    branches: [ main ]
    paths:
      - './backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - './backend/**' 

  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: | 
          npm install
          npm ci

      - name: Build and Run Tests
        run: | 
          npm run build --if-present
          npm run test
      
  deploy_to_docker_hub:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/watcheddit:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
